"""Fix cell-13 in 04_segmentation.ipynb — proper escaping."""

import json
import sys

sys.stdout.reconfigure(encoding="utf-8")

with open("lookalike/04_segmentation.ipynb", encoding="utf-8") as f:
    nb = json.load(f)

# Find the auto_label_segment cell
target_idx = None
for i, cell in enumerate(nb["cells"]):
    src = "".join(cell.get("source", []))
    if "def auto_label_segment" in src or "def _segment_levels" in src:
        target_idx = i
        break

assert target_idx is not None, "Cell not found"

lines = [
    "# ruff: noqa: F821\n",
    "# Пороги на основе реального распределения всей популяции.\n",
    "_label_cols = [\n",
    "    c\n",
    '    for c in ["tx_count", "unique_counterparties", "total_amount",\n',
    '             "active_months", "amount_growth"]\n',
    "    if c in full_df.columns\n",
    "]\n",
    "_q25 = full_df[_label_cols].quantile(0.25)\n",
    "_q75 = full_df[_label_cols].quantile(0.75)\n",
    "_q90 = full_df[_label_cols].quantile(0.90)\n",
    "_q95 = full_df[_label_cols].quantile(0.95)\n",
    "_med = full_df[_label_cols].median()\n",
    "\n",
    "\n",
    "def _segment_levels(profile: pd.Series) -> dict[str, bool]:\n",
    '    """Вычисляет уровни метрик для профиля сегмента."""\n',
    '    tx = profile.get("tx_count", 0)\n',
    '    cp = profile.get("unique_counterparties", 0)\n',
    '    amt = profile.get("total_amount", 0)\n',
    '    act = profile.get("active_months", 0)\n',
    '    grow = profile.get("amount_growth", 0)\n',
    '    dr = profile.get("direction_ratio", 0.5)\n',
    "    return {\n",
    '        "mega_tx": tx >= _q95.get("tx_count", 1e9),\n',
    '        "mega_cp": cp >= _q95.get("unique_counterparties", 1e9),\n',
    '        "high_tx": tx >= _q75.get("tx_count", 1e9),\n',
    '        "high_cp": cp >= _q75.get("unique_counterparties", 1e9),\n',
    '        "high_amt": amt >= _q75.get("total_amount", 1e9),\n',
    '        "growing": grow >= _q75.get("amount_growth", 1e9),\n',
    '        "active": act >= _med.get("active_months", 0),\n',
    '        "declining": grow < _q25.get("amount_growth", -1e9),\n',
    '        "low_tx": tx < _q25.get("tx_count", 0),\n',
    '        "low_cp": cp < _q25.get("unique_counterparties", 0),\n',
    '        "payer": dr >= 0.70,\n',
    '        "receiver": dr <= 0.30,\n',
    '        "balanced": 0.30 <= dr <= 0.70,\n',
    "    }\n",
    "\n",
    "\n",
    "def _ref_potential(lvl: dict[str, bool]) -> tuple[int, str]:\n",
    '    """Composite reference potential score (0-100) + label."""\n',
    "    score = 0\n",
    '    score += 30 if (lvl["mega_tx"] or lvl["mega_cp"]) else 0\n',
    '    score += 20 if (lvl["high_tx"] or lvl["high_cp"]) else 0\n',
    '    score -= 10 if (lvl["low_tx"] and lvl["low_cp"]) else 0\n',
    '    score += 25 if lvl["growing"] else 0\n',
    '    score -= 15 if lvl["declining"] else 0\n',
    '    score += 15 if lvl["active"] else 0\n',
    '    score += 15 if lvl["high_amt"] else 0\n',
    '    score += 15 if lvl["balanced"] else 0\n',
    '    labels = {60: "Высокий", 30: "Средний", 0: "Низкий"}\n',
    "    for threshold, label in labels.items():\n",
    "        if score >= threshold:\n",
    "            return score, label\n",
    '    return score, "Не подходит"\n',
    "\n",
    "\n",
    "# Правила именования: первое совпадение выигрывает\n",
    "_RULES: list[tuple] = [\n",
    '    (lambda lv: lv["mega_tx"] and lv["mega_cp"],\n',
    '     "Мега-хаб (системообразующий)"),\n',
    '    (lambda lv: lv["high_tx"] and lv["high_cp"] and lv["growing"],\n',
    '     "Растущий хаб (активность + рост)"),\n',
    '    (lambda lv: lv["high_tx"] and lv["high_cp"],\n',
    '     "Хаб (много контрагентов, высокая активность)"),\n',
    '    (lambda lv: lv["growing"] and (lv["high_tx"] or lv["high_cp"]),\n',
    '     "Растущий активный (рост + сеть)"),\n',
    '    (lambda lv: lv["growing"],\n',
    '     "Растущий (агрессивный рост оборота)"),\n',
    '    (lambda lv: lv["payer"] and lv["declining"],\n',
    '     "Плательщик (расходы, оборот падает)"),\n',
    '    (lambda lv: lv["payer"],\n',
    '     "Плательщик (преимущественно расходы)"),\n',
    '    (lambda lv: lv["receiver"] and lv["declining"],\n',
    '     "Получатель (входящие, оборот падает)"),\n',
    '    (lambda lv: lv["receiver"],\n',
    '     "Получатель (преимущественно входящие)"),\n',
    '    (lambda lv: lv["high_amt"] and lv["active"],\n',
    '     "Крупный стабильный (объём + регулярность)"),\n',
    '    (lambda lv: lv["low_tx"] and lv["low_cp"] and lv["declining"],\n',
    '     "Неактивный / затухающий"),\n',
    '    (lambda lv: lv["low_tx"] and lv["low_cp"],\n',
    '     "Малоактивный (низкие показатели)"),\n',
    "]\n",
    "\n",
    "\n",
    "def auto_label_segment(profile: pd.Series) -> tuple[str, str]:\n",
    '    """Бизнес-название + потенциал для эталона."""\n',
    "    lvl = _segment_levels(profile)\n",
    "    _, potential = _ref_potential(lvl)\n",
    '    name = "Средний / смешанный профиль"\n',
    "    for cond, label in _RULES:\n",
    "        if cond(lvl):\n",
    "            name = label\n",
    "            break\n",
    "    return name, potential\n",
    "\n",
    "\n",
    "segment_labels = {}\n",
    "segment_potentials = {}\n",
    "for seg_id, row in segment_profiles.iterrows():\n",
    "    name, potential = auto_label_segment(row)\n",
    "    segment_labels[seg_id] = name\n",
    "    segment_potentials[seg_id] = potential\n",
    "\n",
    'full_df["segment_label"] = full_df["behavioral_segment"].map(segment_labels)\n',
    "\n",
    'print("Маркировка сегментов:")\n',
    'print("─" * 75)\n',
    "for seg_id, label in sorted(segment_labels.items()):\n",
    '    n = (full_df["behavioral_segment"] == seg_id).sum()\n',
    "    pct = n / len(full_df) * 100\n",
    "    pot = segment_potentials[seg_id]\n",
    "    pot_icon = {\n",
    '        "Высокий": "✅", "Средний": "⚠️ ",\n',
    '        "Низкий": "❌", "Не подходит": "⛔"\n',
    '    }.get(pot, "?")\n',
    "    print(\n",
    '        f"  Сег. {seg_id} | {n:>5,} ({pct:4.1f}%) | "\n',
    '        f"{pot_icon} Потенциал: {pot:12s} | {label}"\n',
    "    )\n",
    'print("─" * 75)\n',
    'print("\\nПотенциал рассчитан по 6 измерениям:")\n',
    'print("  tx_count, counterparties, growth, active_months, amount, direction")\n',
]

nb["cells"][target_idx]["source"] = lines

with open("lookalike/04_segmentation.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print(f"OK — cell {target_idx} updated")
